### PR TITLE
Introduce V1 of the tutorial

### PR DESCRIPTION
**Pull request by jacobdeery**
Everything is in the README.

To come in the future, hopefully:
- Linting/formatting
- Unit tests in CI

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Yeah this looks good! ty for putting together :) I think my comments are mostly extra info to specify, since I assume this might be reaching some fairly beginner people.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-:-MJewmDU5oBT6tJdqEGX:b7y5w3p)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @jacobdeery)

___
*[README.md, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJeqsVD9drM8-pM8CqS:-MJeqsVEDl9U-3EtMLHt:b-45smi4) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L41)):*
> ```Markdown
> There are a lot of good resources available for learning Git. You might
> find the following helpful:
> - If you like learning interactively, try [Git-It](https://github.com/jlord/git-it-electron).
> ```

Maybe another one worth tossing in, https://learngitbranching.js.org/
It's all interactive in the browser so maybe another option with a little less activation energy than downloading an app.
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJepidT2pn2DZemYmJH:-MJepidU8MyWpnFiBaGy:b-g8op6h) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L43)):*
> ```Markdown
> - If you like learning interactively, try [Git-It](https://github.com/jlord/git-it-electron).
> This interactive tutorial will take you through Git and GitHub basics;
> it will teach you everything you need to know for parts I, IV, and V of
> ```

You can link different parts of a markdown file right? Might be nice to do that when we indicate different parts of the tutorial. Syntax looks like it would be something like
```[I](#part-i-let's-git-started)```
according to [this post](https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown)
___
*[README.md, line 51 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJerIY4BVEeJTAk9hON:-MJerIY4BVEeJTAk9hOO:bba4shw) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L51)):*
> ```Markdown
> 
> You'll also need to create a GitHub account and add it to the Waterloo
> Rocketry GitHub organization. Send your GitHub username to us once
> ```

Might be helpful to say who specifically to send to?
___
*[README.md, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJexHrc5BVcMOeMk-VW:-MJexHrd3oN7bzvtva1g:b-xf82zi) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L75)):*
> ```Markdown
> libraries that other people have written and made available for you to
> use. For `sandbox`, we only have one dependency: `pytest`, the tool we
> use to test the code. Run these two commands to complete the
> ```

`Run these two commands at the root of the repo...`? I like to specify because my idiot ass didn't know that location mattered when I first started coding lmao what a disaster
___
*[README.md, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJetbP22nDhtM5l5L4t:-MJetbP38uNpqIiA4Foj:b-1oj5i7) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L78)):*
> ```Markdown
> installation process:
> ```
> pip install -U -r requirements.txt
> ```

Might also be worth mentioning that on Mac (possibly Linux?) it's `pip3`, since Python 2 comes automatically installed for some reason. If you'd like, I can poke around a bit and add more Mac/Linux specific information throughout the readme once we have this in?
___
*[README.md, line 117 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJeuDcx9Jy1m_FN8qYI:-MJeuDcx9Jy1m_FN8qYJ:b-fkiyb5) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L117)):*
> ```Markdown
> 
> Next, write a unit test for your new function and add it to
> `test_sandbox.py`. Again, follow the examples that are already there.
> ```

Also maybe worth explicitly mentioning that the test function name should start with `test`, since it "fails" pretty silently if not - the test just won't run.
___
*[README.md, line 162 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJev07y7x-d3ZppX1In:-MJev07y7x-d3ZppX1Io:b-q5ezgh) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L162)):*
> ```Markdown
> 
> By committing your change, you've stored it in the local history of the
> repository, but you haven't yet merged it into `master`. In order to
> ```

I feel like the comparison with local history conflates pushing to remote and merging to master? Maybe worth separating, but this is very much a nitpick.
___
*[README.md, line 178 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJewFZV1sRtC5O_0K05:-MJew7aM19RUbTzVBgBT:b-9dwdup) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L178)):*
> ```Markdown
> - You've had your pull request reviewed and have addressed any review
> comments
> - You've merged your pull request into the `master` branch
> ```

We could add a conclusion to match the intro, just a quick "congrats you're done, talk to software people for projects or check out our good first issues (with link)"
___
*[sandbox/sandbox.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJewb0NBZTU4qe87POe:-MJewb0NBZTU4qe87POf:beerez6) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/sandbox/sandbox.py#L1)):*
> ```Python
> def add_one(val):
> ```

Docstring? If we're going by-the-book here?

**Review by dwkletke — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1)* status: all files reviewed, 15 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgcpkoAt5NI73f7pd8:-MJgcpkoAt5NI73f7pd9:b1jwc4o) (no related file):*
I agree with Wendi, I think this is a great resource for new members! Most of my comments are small nitpicks that could be ignore if you don't think they are necessary!

---
___
*[.gitignore, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgTkz8DRlvLsAYZRuw:-MJgTkz8DRlvLsAYZRux:be4n0v5) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/.gitignore#L14)):*
> ```ignore
> __pycache__/
> *.py[cod]
> *.egg-info/
> ```

Maybe add `.pytest_cache/` if `pytest` unit tests are expected? 
___
*[README.md, line 72 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgY2DA23xAR_UcF8Ga:-MJgY2DA23xAR_UcF8Gb:b9dupxi) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L72)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> In most cases, working on a Python project means installing dependencies
> using `pip`. Pip is a tool for installing Python packages - software
> libraries that other people have written and made available for you to
> use. For `sandbox`, we only have one dependency: `pytest`, the tool we
> ```
</details>

Might be a good idea to mention `pip` is already installed with Python since the recommended Python version >= 3.7? I feel like people who aren't familiar with Python might be wondering if/how they need to install `pip`.
___
*[README.md, line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgbVT74XXWLQEgxdsm:-MJgbVT74XXWLQEgxdsn:bbu7mdh) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L94)):*
> ```
> start by running the `pytest` command
> ```
As a beginner programmer I feel like I was pretty stupid and wouldn't have the intuitive sense to know that when you say `...start by running the pytest command`, that it should be run in whichever terminal I am using. Might be good to say something like: `...start by running the pytest command in your terminal`, and we could even mention at the root of the repo or something. Although, this might be pretty obvious to most so feel free to do whatever you feel is best.
___
*[README.md, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgbZPa4haE-oLAWg1E:-MJgbZPa4haE-oLAWg1F:b12xpoz) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L95)):*
> ```
> automatically detect and run all of the unit tests in the repository
> ```
Kind of tagging off of Wendi's comment below, but there might be some benefit mentioning that `pytest` automatically detects and runs unit tests from `test_*.py` or `*_test.py` files? However, this could very well be out of the scope of this tutorial.
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgc-ih4V8SwZM4iwDo:-MJgc-ih4V8SwZM4iwDp:b-fqhqlt) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L114)):*
> ```
> - it has well-defined inputs and outputs
> ```
Very small nit: On the page it looks kind of odd/confusing with all of the dashes. Might want to switch to brackets or even a colon? Totally up to you.

This is what I am referencing:

___
*[README.md, line 162 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJev07y7x-d3ZppX1In:-MJgdDoe1LGGCmh7KtAZ:bhpfrxi) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L162)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I feel like the comparison with local history conflates pushing to remote and merging to master? Maybe worth separating, but this is very much a nitpick.
</blockquote></details>

I agree with this.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1)* status: all files reviewed, 7 unresolved discussions (waiting on @dwkletke, @jacobdeery, and @wendi-yu)

___
*[.gitignore, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgTkz8DRlvLsAYZRuw:-MJhE1ab8Mjeu28VXd_H:b-3vru03) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/.gitignore#L14)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

Maybe add `.pytest_cache/` if `pytest` unit tests are expected? 
</blockquote></details>

`.pytest_cache/` automatically gitignores itself, so we don't need to ignore it separately.
___
*[README.md, line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJeqsVD9drM8-pM8CqS:-MJhEt3L-6h0ae_V7oC1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L41)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Maybe another one worth tossing in, https://learngitbranching.js.org/
It's all interactive in the browser so maybe another option with a little less activation energy than downloading an app.
</blockquote></details>

Done.
___
*[README.md, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJepidT2pn2DZemYmJH:-MJhEtfg6SYCdo23LF5O:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L43)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

You can link different parts of a markdown file right? Might be nice to do that when we indicate different parts of the tutorial. Syntax looks like it would be something like
```[I](#part-i-let's-git-started)```
according to [this post](https://stackoverflow.com/questions/2822089/how-to-link-to-part-of-the-same-document-in-markdown)
</blockquote></details>

Done.
___
*[README.md, line 51 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJerIY4BVEeJTAk9hON:-MJhEzbn10ysXhLuPNTF:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L51)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Might be helpful to say who specifically to send to?
</blockquote></details>

Done.
___
*[README.md, line 72 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgY2DA23xAR_UcF8Ga:-MJhF7i1C_b5kYeGfwZW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L72)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> In most cases, working on a Python project means installing dependencies
> using `pip`. Pip is a tool for installing Python packages - software
> libraries that other people have written and made available for you to
> use. For `sandbox`, we only have one dependency: `pytest`, the tool we
> ```
Might be a good idea to mention `pip` is already installed with Python since the recommended Python version >= 3.7? I feel like people who aren't familiar with Python might be wondering if/how they need to install `pip`.
</blockquote></details>

Done.
___
*[README.md, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJexHrc5BVcMOeMk-VW:-MJhFReB9bzzBTlgNn2l:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L75)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

`Run these two commands at the root of the repo...`? I like to specify because my idiot ass didn't know that location mattered when I first started coding lmao what a disaster
</blockquote></details>

Done.
___
*[README.md, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJetbP22nDhtM5l5L4t:-MJhFewh1WHe2gG67CfP:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L78)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Might also be worth mentioning that on Mac (possibly Linux?) it's `pip3`, since Python 2 comes automatically installed for some reason. If you'd like, I can poke around a bit and add more Mac/Linux specific information throughout the readme once we have this in?
</blockquote></details>

Done.
___
*[README.md, line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgbVT74XXWLQEgxdsm:-MJhFpl931pkmTaaZxZ_:b-qu6n94) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L94)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> start by running the `pytest` command
> ```
As a beginner programmer I feel like I was pretty stupid and wouldn't have the intuitive sense to know that when you say `...start by running the pytest command`, that it should be run in whichever terminal I am using. Might be good to say something like: `...start by running the pytest command in your terminal`, and we could even mention at the root of the repo or something. Although, this might be pretty obvious to most so feel free to do whatever you feel is best.
</blockquote></details>

Good point. Done.
___
*[README.md, line 95 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgbZPa4haE-oLAWg1E:-MJhFy2d1bd3xoxaPved:b-410bcb) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L95)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> automatically detect and run all of the unit tests in the repository
> ```
Kind of tagging off of Wendi's comment below, but there might be some benefit mentioning that `pytest` automatically detects and runs unit tests from `test_*.py` or `*_test.py` files? However, this could very well be out of the scope of this tutorial.
</blockquote></details>

I'll leave this one out for now, but I'll add it to the "intro to unit testing" doc that I'm working on.
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJgc-ih4V8SwZM4iwDo:-MJhG8Po0RzABNgmJ4St:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L114)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> - it has well-defined inputs and outputs
> ```
Very small nit: On the page it looks kind of odd/confusing with all of the dashes. Might want to switch to brackets or even a colon? Totally up to you.

This is what I am referencing:


</blockquote></details>

Done.
___
*[README.md, line 117 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJeuDcx9Jy1m_FN8qYI:-MJhGENV20sqYbstUcDL:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L117)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Also maybe worth explicitly mentioning that the test function name should start with `test`, since it "fails" pretty silently if not - the test just won't run.
</blockquote></details>

Done.
___
*[README.md, line 162 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJev07y7x-d3ZppX1In:-MJhHna_2bdlnWj4Ghhm:bf3u0tu) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L162)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

I agree with this.
</blockquote></details>

I separated the two steps and hopefully made it a bit more clear. Let me know if this looks good.
___
*[README.md, line 178 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJewFZV1sRtC5O_0K05:-MJhM6sd0eW8zl2TR6cj:b-896fix) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L178)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

We could add a conclusion to match the intro, just a quick "congrats you're done, talk to software people for projects or check out our good first issues (with link)"
</blockquote></details>

Done.
___
*[sandbox/sandbox.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJewb0NBZTU4qe87POe:-MJhJCBo5BdvGZ1lMmGl:bituy00) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/sandbox/sandbox.py#L1)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Docstring? If we're going by-the-book here?
</blockquote></details>

Done, and added a section to Part III on docstrings.

**Review by dwkletke — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-:-MJhPxu5ChaMaCs0EoBU:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @jacobdeery and @wendi-yu)

___
*[README.md, line 162 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJev07y7x-d3ZppX1In:-MJhNHUh69vScv8xqb36:b-cx1bry) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/a002db9af71b60ac64ce512655a333915e7742e2/README.md#L162)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

I separated the two steps and hopefully made it a bit more clear. Let me know if this looks good.
</blockquote></details>

Yeah I think this is clearer. I like the approach since I don't think it is necessary to try and explain the whole local vs remote versions in this tutorial (people will probably see it online in one of the resources linked in this tutorial)!
___
*[README.md, line 89 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJhQ4lE24bbhsQoeBXg:-MJhQ4lE24bbhsQoeBXh:bh6lnkt) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b082db24db3e4eac65bd99398db4f52fa8a89764/README.md#L89)):*
> ```
> If you're using a Mac
> ```
I don't think you _need_ to add this since if someone was running Linux they would probably already know this, but IIRC Linux distributions use `pip3` for Python 3 as well (well at least in my experience with Ubuntu). You might know better than me though.

**Review by wendi-yu — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-:-MJhSp287O8D1eTQid9F:bb6ywmx)* status: all files reviewed, 2 unresolved discussions (waiting on @dwkletke and @jacobdeery)

___
*[README.md, line 89 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJhQ4lE24bbhsQoeBXg:-MJhROpL-onOREZx6fcj:b-1hvbzh) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b082db24db3e4eac65bd99398db4f52fa8a89764/README.md#L89)):*
<details><summary><i>Previously, dwkletke (Dawson Kletke) wrote…</i></summary><blockquote>

> ```
> If you're using a Mac
> ```
I don't think you _need_ to add this since if someone was running Linux they would probably already know this, but IIRC Linux distributions use `pip3` for Python 3 as well (well at least in my experience with Ubuntu). You might know better than me though.
</blockquote></details>

Yeah, I checked on the student CS environment and they do. Looks like `pip` by itself gets you the Python 2 pip, so it doesn't fail per se either, it might just cause confusing problems down the line. I think it's worth leaving in, doesn't hurt to provide a bit of extra information?

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @dwkletke)

___
*[README.md, line 89 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/1#-MJhQ4lE24bbhsQoeBXg:-MJhUSFTDo5GUgdb3QC1:bcw3oj9) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b082db24db3e4eac65bd99398db4f52fa8a89764/README.md#L89)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Yeah, I checked on the student CS environment and they do. Looks like `pip` by itself gets you the Python 2 pip, so it doesn't fail per se either, it might just cause confusing problems down the line. I think it's worth leaving in, doesn't hurt to provide a bit of extra information?
</blockquote></details>

"Linux distributions use pip3 for Python 3" is a bit too broad of a statement. It's true that Ubuntu 18.04 and earlier aliased `python` to `python2` and `pip` to `pip2` by default, but this is no longer the case for 20.04 and later releases, given that Python 2 is fully deprecated (not sure about releases in between the two). [PEP 394](https://www.python.org/dev/peps/pep-0394/) has more background if you're curious.

Added info on Linux regardless.

**Pull request merged**
