### PR TITLE
Add note for windows about formatting bash script

### PR DESCRIPTION
**Pull request by Awbmilne**
Currently, there is a formatting bash script in the onboarding repository, but no notes about how to run it on a windows system. Hopefully someone who is looking to help on the team has worked with Linux or knows about WSL, but notation should be provided for those less aware.

Yeah, Yeah ... I use windows. I'm a Mech,I need it for Solidworks and such.

This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8)

### CODE REVIEW

**Comment by jacobdeery** [comment]
I recommend just installing Git for Windows and using [Git Bash](https://git-scm.com/downloads); I'm on Windows and I find this to be the easiest option by far.

**Comment by Awbmilne** [comment]
Great suggestion, also suggested by @wendi-yu 
Just so used to WSL that I forget about git bash.

**Review by jacobdeery — COMMENTED** [review]
Thanks for adding this! The content looks good to me, I've just corrected some typos and left one longer pedantic point of clarification.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-:-M_imCnz6cESkaqjCwK3:b-lmf3h8)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @Awbmilne)

___
*[README.md, line 240 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_ih9WE9M9jPxMqgRqy:-M_ih9WE9M9jPxMqgRqz:b-deu3rq) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L240)):*
> ```
> The formatting script in this repository is written in bash. Unfortunately,
> Windows is derived from DOS while Linux and Mac are derived from UNIX, this means
> there are some incompatibilities. Namely, you cant run bash (`.sh`) scripts on native Windows.
> ```

This is conceptually correct, but I'm going to be a bit pedantic and clarify some details.

Bash is a shell (like command prompt or Powershell), and a Bash script is a set of commands to be run by a Bash shell. Some of these commands (like `echo`) are built into the shell itself; other commands (like `cat`) are external programs, many of which are part of the [`coreutils` package](https://en.wikipedia.org/wiki/GNU_Core_Utilities). This is a few levels above the real fundamental "incompatibilities" (the kernel, etc.) between Windows and Unix.

The reason that most people wouldn't be able to run a Bash script on Windows is because they don't have anything installed that can interpret the Bash script, not because Windows and Bash are fundamentally incompatible. It's the same reason that most people wouldn't be able to open a `.sldprt` file - they don't have the right program installed. When you run a Bash script in Git Bash, you're still running native Windows; there's no emulation or virtualization going on, you've just installed a new shell and a bunch of new programs for all of your useful shell commands.

Anyways, none of this really affects the fix for the issue (which is to, one way or another, install Bash); I just wanted to give you a bit more info on what exactly is going on.
___
*[README.md, line 246 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_ilvPl-LDGLC0w-Zop:-M_ilvPl-LDGLC0w-Zoq:btoims5) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L246)):*
> ```
> windows subsystem for linux
> ```
Windows Subsystem for Linux
___
*[README.md, line 246 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_ilxEX3FH-eFiuvnip:-M_ilxEX3FH-eFiuvniq:bpr7me7) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L246)):*
> ```
> linux
> ```
Linux
___
*[README.md, line 246 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_ilydg8QKro7_ftFsv:-M_ilydg8QKro7_ftFsw:bgrsr25) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L246)):*
> ```
> windows
> ```
Windows
___
*[README.md, line 247 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_ilzmZ0C0aKVaYA_V3:-M_ilzmZ0C0aKVaYA_V4:bd92g7y) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L247)):*
> ```
> dont
> ```
don't
___
*[README.md, line 247 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_im1y40G0Rbi_hfFfT:-M_im1y40G0Rbi_hfFfU:bpr7me7) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L247)):*
> ```
> linux
> ```
Linux
___
*[README.md, line 247 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_im30H9HuSW5tG4noh:-M_im30H9HuSW5tG4noi:bhyc0q7) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L247)):*
> ```
> python dependacies
> ```
Python dependencies
___
*[README.md, line 247 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_im55U0Q8Qboekq2ic:-M_im55U0Q8Qboekq2id:b-rusb42) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L247)):*
> ```
> linux environement
> ```
Linux environment
___
*[README.md, line 247 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/8#-M_im6rU-nqulEwNrbnU:-M_im6rU-nqulEwNrbnV:bgrsr25) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/b567e0c3debb6e500b5a6c73559b1d927106ba7f/README.md#L247)):*
> ```
> windows
> ```
Windows

**Comment by Awbmilne** [comment]
Pedantic but true. 
I'll reword some of it to better reflect reality, rather than just end-user experience.

**Pull request closed without merging**
