### PR TITLE
Austin W. Milne Onboarding

### PR DESCRIPTION
**Pull request by Awbmilne**
Add function for getting fibonnaci value by index.
Add the requisite unit test for the function.

Onboarding task for Austin W. Milne 👍

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Cool looks great to me! Just a few nitpicks, otherwise lgtm :)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7#-:-M_iMKxN-BawDLoqe6dl:blu6k9e)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Awbmilne)

___
*[sandbox/sandbox.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7#-M_iLAP1DJM6suo8nvZZ:-M_iLAP23khChRNBGRUu:b9446z0) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/bb51c4ea65cafbed1e423aea8c345188150d0f39/sandbox/sandbox.py#L35)):*
> ```Python
> def fibonacci_by_index(index: int):
>     """
>     Get the value at the index of the fibonacci series.
> ```

Nitpick but I think Fibonacci should be capitalized in the docstring/comments (not necessary for the fn name tho)? Also you don't have to do the git signoff thing on the commits or in the comments, we'll use git blame if we really have to track someone down haha
___
*[sandbox/tests/test_sandbox.py, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7#-M_iLtGqEdyCtT4SEyMr:-M_iLtGrEaPSsURq3Bld:bki1379) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/bb51c4ea65cafbed1e423aea8c345188150d0f39/sandbox/tests/test_sandbox.py#L17)):*
> ```Python
>     indexs = (0, 1, 2, 3, 19, 35, 74, 100)
>     values = (0, 1, 1, 2, 4181, 9227465, 1304969544928657, 354224848179261915075)
>     for index, val in zip(indexs, values):
> ```

woah the zip thing is cool! Should `indexs` be `indices` or `indexes` though?

**Comment by Awbmilne** [comment]
Great points, software requires grammar too. 😆

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Awbmilne)

___
*[sandbox/sandbox.py, line 50 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7#-M_iQVACDZJT_c7x_9t1:-M_iQVACDZJT_c7x_9t2:bx7p9kd) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/03007d883809a6da9dd1cbf271543db4bc3deb3d/sandbox/sandbox.py#L50)):*
> ```Python
>     if (index < 0):
>         raise IndexError("Invalid Fibonacci Index")
>         return -1
> ```

Returning -1 isn't necessary; you've already raised an `IndexError`, so this code should be unreachable

**Comment by Awbmilne** [comment]
True, under most circumstances, you would not reach the return statement. But it is possible that someone could suppress the warning using:
```python
with suppress(IndexError):
   # call to fibonacci_by_index
```

Though, why anyone would suppress index errors is beyond me.

**Comment by jacobdeery** [comment]
I don't think that's correct. Try running this code (I assume your `suppress` is coming from `contextlib` and not some other source):

```python
import contextlib as cl
import sandbox as sb

result = 100

with cl.suppress(IndexError):
    result = sb.fibonacci_by_index(-1)

print(result)
```

The error is suppressed, yes, but the return statement is still not reached; this code prints `100` instead of the `-1` that would be expected if the function returned. `cl.suppress` is equivalent to a simple `try`/`except`, which resumes execution in the outer scope (the first line outside of the `with` block).

**Comment by Awbmilne** [comment]
Right, I guess my python is rustier than I had thought.

Contextlib documentation for reference: [contextlib.suppress](https://docs.python.org/3/library/contextlib.html#contextlib.suppress)

**Review by wendi-yu — APPROVED** [review]
cool lgtm! squash and merge and youll be good :) (and I guess follow the commit message format but I'm sure you know that lol)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/7#-:-M_wzRfA1Ro5JdaLfvGH:b-uv3vt4)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Awbmilne)

**Comment by Awbmilne** [comment]
Aww man, I gotta merge using Github UI 😕

**Pull request merged**
