### PR TITLE
Created new function and unit test

### PR DESCRIPTION
**Pull request by Chrisc110**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
The unit test looks fine here, but you've added the function in the wrong place; it should be in `sandbox/sandbox.py`, not `sandbox/tests/sandbox.py`

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-:-MMcEZ469AwvJCbxwFLO:b-dncaxd)* status: 0 of 2 files reviewed, all discussions resolved

**Review by wendi-yu — COMMENTED** [review]
My comments are mostly just formatting nitpicks. Function looks good :) The commit message should also be in the imperative, so "Create new function and unit test" for this commit.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-:-MMcVaYhEnYHAwDG2oT-:byj88mi)* status: 0 of 2 files reviewed, all discussions resolved

___
*[sandbox/tests/sandbox.py, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-MMcV0zh5jN8Oam0U8kq:-MMcV0zi6eJ0f1ZHjuvI:bf7mq4c) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/618b41b81d1ce86786248cde56f8cf47c5b39434/sandbox/tests/sandbox.py#L18)):*
> ```Python
> def add_two(val):
>     """
>     Adds 2 to a number.
> ```

Docstrings should typically be in the imperative (see [this](https://www.python.org/dev/peps/pep-0257/#one-line-docstrings) PEP), which basically means you want to be telling the program to do something, ie "Add 2 to a number."
___
*[sandbox/tests/sandbox.py, line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-MMcVMRd1TG7f4ar5hRi:-MMcVMReCr73C4WpmQfm:b-4kbgnu) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/618b41b81d1ce86786248cde56f8cf47c5b39434/sandbox/tests/sandbox.py#L23)):*
> ```Python
>     ----------
>     val: number
>         The number to which one should be added.
> ```

to which two should be added?
___
*[sandbox/tests/sandbox.py, line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-MMcVSqD-yqYYiphODNu:-MMcVSqD-yqYYiphODNv:b8i732p) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/618b41b81d1ce86786248cde56f8cf47c5b39434/sandbox/tests/sandbox.py#L29)):*
> ```Python
>     The number plus two.
>     """
>     return val + 2
> ```

Final newline :0
___
*[sandbox/tests/test_sandbox.py, line 10 at r1](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-MMcVViL2g4yLxYfl41C:-MMcVViL2g4yLxYfl41D:b-dsjocw) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/618b41b81d1ce86786248cde56f8cf47c5b39434/sandbox/tests/test_sandbox.py#L10)):*
> ```Python
> def test_add_two():
>     val = 1
>     assert sb.add_two(val) == 3
> ```

Also newline here

**Review by wendi-yu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jacobdeery and @wendi-yu)

___
*[sandbox/sandbox.py, line 30 at r2](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3#-MMnRS8o633VpGjVt8jC:-MMnRS8o633VpGjVt8jD:b9aky92) ([raw file](https://github.com/waterloo-rocketry/software-onboarding/blob/4ca0756123f873622f3ce18681f744f935171950/sandbox/sandbox.py#L30)):*
> ```Python
>     """
>     return val + 2
>     
> ```

One last nitpick - there are a few extraneous whitespaces on the last line here, same with `test_add_two`. I think if you remove these we should be good to go :0

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/software-onboarding/3)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jacobdeery)

**Pull request merged**
